### ISSUE TITLE
怎么用GradManager()实现WGAN-GP中的梯度惩罚损失？

### ISSUE THREAD

**Issue by miemie2013** [MegEngine/Documentation#388]
## 文档链接
[](https://www.megengine.org.cn/doc/stable/zh/reference/api/megengine.autodiff.GradManager.html?highlight=gradmanager)

## 问题描述
你好，文档中只提到了一句“要同时进行多种微分或进行高阶微分，可根据需要创建尽可能多的 GradManager。”但是没有代码示例。如果是pytorch，用torch.autograd.grad()求出一阶梯度，然后一阶梯度再参与损失的计算。在MegEngine中要怎么实现？谢谢解答！

**Comment by MegChai** [comment]
你好，高阶导相关的文档内容页面还没有发布，大致内容如下：

## with gm ：with gm2

gm 嵌套 gm2 的GradManager求二阶导，从外部gm的视角来看，它并不关心求导对象是在 backward 阶段产生还是从 forward 阶段产生的，只要是在 gm scope 内的计算都会被记录下来，如下图所示：

![image](https://user-images.githubusercontent.com/21091736/159444250-c0b56475-8524-4f6f-99ac-1f056f764d55.png)

```python
#with gm ：with gm2 代码示例

# 这里想求x.grad对x的梯度(grad(x, grad(x, y)))
def test_2nd_grad_with_manager():
    x_np = np.random.rand(10).astype("float32")
    x = mge.tensor(x_np)

    gm = GradManager().attach([x])
    gm2 = GradManager().attach([x])

    with gm: #gm在gm2外部，因此gm可以观测到gm2的backward行为
        with gm2:
            y = F.cos(x) #forward
            gm2.backward(y)
            x_grad = x.grad
            x.grad = None
            np.testing.assert_almost_equal(x_grad.numpy(), -np.sin(x_np), decimal=5)
            gm.backward(x_grad) #x.grad是通过gm2.backward算出来的，计算路径对gm可见
    np.testing.assert_almost_equal(
       x.grad.numpy(), -np.cos(x_np), decimal=5
    )
```

## with gm2 ：with gm

我们调换gm与gm2的顺序，可以看到，在gm.backward()之后，x.grad为空，也就是说gm没有求出x对x.grad的梯度。这是因为此时gm被放在内层，无法观测到gm2.backward这个行为。因此在gm眼里x.grad就好似凭空产生的，当然无法对其求导。

![image](https://user-images.githubusercontent.com/21091736/159444333-9cb3d8fe-1ea7-422c-bbca-e31df9449102.png)


```python
#with gm2 ：with gm 代码示例

# expect grad(x, grad(x, y)), got None
def test_2nd_grad_fail_with_manager():
    x_np = np.random.rand(10).astype("float32")
    x = mge.tensor(x_np)

    gm = GradManager().attach([x])
    gm2 = GradManager().attach([x])

    with gm2: #注意此处
        with gm: #此时gm与gm2位置互换，放在内层
            y = F.cos(x)
            x_grad = gm2.backward(y)
            x.grad = None
            np.testing.assert_almost_equal(x_grad.numpy(), -np.sin(x_np), decimal=5)
            gm.backward(x.grad)

        assert x.grad is None
```

**Comment by miemie2013** [comment]
> ```python
>  F.co
> ```

没有。
```

    with gm:
        with gm2:
            # styles = model(ws)
            styles = F.cos(ws)
            styles2 = F.sigmoid(styles)

            gm2.backward(styles2)
            dstyles2_dws = ws.grad
            ws.grad = None

            loss = dstyles2_dws.sum() + styles2.sum()
            gm.backward(loss)
```

报错
Traceback (most recent call last):
  File "D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge.py", line 47, in <module>
    styles = F.cos(ws)
  File "D:\Python38\lib\site-packages\megengine\functional\elemwise.py", line 290, in cos
    return _elwise(x, mode=Elemwise.Mode.COS)
  File "D:\Python38\lib\site-packages\megengine\core\tensor\array_method.py", line 75, in _elwise
    return _elwise_apply(args, mode)
  File "D:\Python38\lib\site-packages\megengine\core\tensor\array_method.py", line 41, in _elwise_apply
    (result,) = apply(op, *args)
RuntimeError: Unknown exception

**Comment by MegChai** [comment]
你这个代码提供的信息不够，不能算作是“最小复现”，建议另外在 MegEngine repo 的 Issue 或 MegEngine 官方论坛发新的代码执行 Bug 反馈帖，给出可稳定复现的例程序。单纯看报错 `styles = F.cos(ws)` 这一步就已经出问题了（信息不够，比如上下文中得到的 `styles` 是啥形状？），整个还没有执行到 `backward` 处。

**Comment by miemie2013** [comment]
> 你这个代码提供的信息不够，不能算作是“最小复现”，建议另外在 MegEngine repo 的 Issue 或 MegEngine 官方论坛发新的代码执行 Bug 反馈帖，给出可稳定复现的例程序。单纯看报错 `styles = F.cos(ws)` 这一步就已经出问题了（信息不够，比如上下文中得到的 `styles` 是啥形状？），整个还没有执行到 `backward` 处。

比如这样
```
import megengine as mge
import megengine.functional as F
import megengine.module as M
import numpy as np
from megengine.autodiff import GradManager



class FullyConnectedLayer(M.Module):
    def __init__(self,
        in_features,                # Number of input features.
        out_features,               # Number of output features.
        bias            = True,     # Apply additive bias before the activation function?
        activation      = 'linear', # Activation function: 'relu', 'lrelu', etc.
        lr_multiplier   = 1,        # Learning rate multiplier.
        bias_init       = 0,        # Initial value for the additive bias.
    ):
        super().__init__()
        self.activation = activation
        self.weight = mge.Parameter(mge.tensor(np.random.randn(out_features, in_features).astype(np.float32)) / lr_multiplier)
        self.bias = mge.Parameter(mge.tensor(np.ones(out_features, ).astype(np.float32) * bias_init)) if bias else None
        self.weight_gain = lr_multiplier / np.sqrt(in_features)
        self.weight_gain = float(self.weight_gain)
        self.bias_gain = lr_multiplier

    def forward(self, x):
        w = self.weight * self.weight_gain
        b = self.bias
        if b is not None:
            if self.bias_gain != 1:
                b = b * self.bias_gain
        out = F.matmul(x, w, transpose_b=True) + F.expand_dims(b, 0)
        return out



batch_size = 2
in_channels = 512
w_dim = 512
lr = 0.0001
activation = 'sigmoid'

model = FullyConnectedLayer(w_dim, in_channels, activation=activation, bias_init=1)


model.train()
optimizer = mge.optimizer.SGD(model.parameters(), lr=lr, momentum=0.9)


for batch_idx in range(20):
    print('======================== batch_%.3d ========================'%batch_idx)
    optimizer.zero_grad()

    ws = np.random.randn(batch_size, 512)
    ws = mge.tensor(ws)
    ws.stop_gradient = False

    gm = GradManager().attach([ws])
    gm2 = GradManager().attach([ws])


    with gm:
        with gm2:
            styles = model(ws)
            # styles = F.cos(ws)
            styles2 = F.sigmoid(styles)

            gm2.backward(styles2)
            dstyles2_dws = ws.grad
            ws.grad = None

            loss = dstyles2_dws.sum() + styles2.sum()
            gm.backward(loss)
    optimizer.step()
print()
```
我要把一阶梯度和styles2作为损失训练网络，但是报错：
```
D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge222.py:52: DeprecationWarning: Call to deprecated method zero_grad. (use clear_grad instead) -- Deprecated since version 1.0.
  optimizer.zero_grad()
Traceback (most recent call last):
  File "D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge222.py", line 64, in <module>
    styles = model(ws)
  File "D:\Python38\lib\site-packages\megengine\module\module.py", line 148, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:/GitHub/ppgan/test_grad/test2_01_FullyConnectedLayer_grad_mge222.py", line 32, in forward
    out = F.matmul(x, w, transpose_b=True) + F.expand_dims(b, 0)
  File "D:\Python38\lib\site-packages\megengine\functional\math.py", line 1069, in matmul
    (result,) = apply(extentedMatrixMulOp(), inp1, inp2)
RuntimeError: Unknown exception
```
谢谢解答！

**Comment by MegChai** [comment]
为了方便其它人检索，请把楼上的帖子拆分到 MegEngine/MegEngine repo 下作为新的独立 Issue.

本 Issue 用于解决缺乏 Documentation 中缺乏高阶导用法的问题。
